spring:
  datasource:
    url: jdbc:oracle:thin:@//oracle-host:1521/ORCLCDB
    username: commerce
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.OracleDialect
