apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: order-svc-dr
spec:
  host: order-svc
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 1000
        maxRequestsPerConnection: 100
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
  subsets:
    - name: v1
      labels: {{ version: v1 }}
    - name: v2
      labels: {{ version: v2 }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: order-svc-vs
spec:
  hosts: [ "order-svc" ]
  http:
    - timeout: 3s
      retries:
        attempts: 2
        perTryTimeout: 1s
        retryOn: gateway-error,connect-failure,refused-stream,5xx
      route:
        - destination: {{ host: order-svc, subset: v1, port: {{ number: 80 }} }}
          weight: 90
        - destination: {{ host: order-svc, subset: v2, port: {{ number: 80 }} }}
          weight: 10
